### ISSUE TITLE
Не экспортирует

### ISSUE THREAD

**Issue by aolko** [coldmind/vk-dialogue-export.py#3]
```
Authorized vk
Traceback (most recent call last):
  File "vk-dialogue-export.py", line 52, in <module>
    messages = _api("messages.getHistory", [(selector, messages_id)], token)
  File "vk-dialogue-export.py", line 17, in _api
    return json.loads(urllib2.urlopen(url).read())["response"]
KeyError: 'response'
```

**Comment by coldmind** [comment]
Works for me.
Please add more details.
Maybe vk application is not working for you, you can create your own and use it.
